### ISSUE TITLE
error in the code:   uint8_t light = mtb_light_sensor_light_level(&light_sensor_obj));

### ISSUE THREAD

**Issue by vinayyn7** [cypresssemiconductorco/sensor-light#1]
**Prerequisites**

Can you reproduce the problem reliably?

Did you check current release notes for known issues?

If this is not the latest release, have you checked newer releases? 

**Description**:

**Steps to Reproduce:**

1.

2.

3.

**Expected Result:**

**Actual Result:**

**Frequency (1/1, 1/50, 1/100):**

**Build/Commit:**

Please specify the release, like 1.4.1. If there is no release, give us the commit for the code you used.

**Target:**

The chip or kit you are working with

**Host OS and Version:**

MacOS, Windows, Linux

**Compiler:**

Include the version!

**Environment**

Provide the context surrounding this problem. Perhaps an IDE, a debug probe, an RTOS, etc. (and versions)

**Comment by ddka22** [comment]
Hello @vinayyn7,

I believe you are referring to the error in the code snippet in the README.md file. Thank you for bringing this up. I have raised an internal ticket to get this fixed. Appreciate the feedback.

Regards,
Dheeraj

**Comment by ddka22** [comment]
Internal reference: https://jira.cypress.com/browse/BSP-2654

**Comment by ddka22** [comment]
Hello @vinayyn7,

The code snippet should have been:
mtb_light_sensor_t **light_sensor**;
...
...
rslt = mtb_light_sensor_init(&**light_sensor**, &adc, LIGHT_SENSOR_PIN);
CY_ASSERT(rslt == CY_RSLT_SUCCESS);
 
uint8_t light = mtb_light_sensor_light_level(&**light_sensor**);

Please use this modification until the corrections are made. 

Regards,
Dheeraj

**Comment by ralphjy** [comment]
Has anyone got this code to work with the CY8CKIT-062-WiFi-BT PSoC 6 WiFi-BT Pioneer Kit?

It gets to this line:  uint8_t light = mtb_light_sensor_light_level(&light_sensor);
and starts running a Thread in mtb-example-psoc6-capsense-buttons-slider.elf and never continues.

Any idea what is happening?

Thanks,
Ralph

**Comment by rmbk19** [comment]
Hi @ralphjy,

I created a simple project following the readme instructions. Please let me know if this works for you.
[ambient-light-sensor.zip](https://github.com/cypresssemiconductorco/sensor-light/files/5865685/ambient-light-sensor.zip)

Regards,
Rakshith

**Comment by vinayyn7** [comment]
code is working fine. i have attached the serial port data on the below
file.
*Thanks and Regards*

*Vinay Y.N*

**Comment by ralphjy** [comment]
Hi Rakshith,

The project that you sent works fine.  The problem that I was having seems related to to the fact that I had some code before the _enable_irq(); in my project.

Thanks,
Ralph
